# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 9081
  servlet:
    context-path: /admin

## mysql
spring:
  ## 环境 dev|test|prod
  profiles:
    active: dev

##去掉html的校验
thymeleaf:
    cache: false
    mode: LEGACYHTML5