# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9080
  servlet:
    context-path: /api

## mysql
spring:
  ## 环境 dev|test|prod
  profiles:
    active: dev
